### ISSUE TITLE
Testing issue for comments

### ISSUE THREAD

**Issue by SusannaLange** [chicago-cdac/textbook-datascience-1#7]
Testing this 'issues' option for commenting purposes. Is this where we want to leave editing comments to each other?

**Comment by amandakube** [comment]
Testing replys

**Comment by jesteria** [comment]
Hello! Thanks for the test :slightly_smiling_face: 

Should branches and Pull Requests be used, then it would be most convenient for such conversations to occur there in the Pull Request, prior to work being merged in.

Regardless, yes, any "issues" with work that's been merged may certainly be discussed here!
